#########################
# project configuration #
#########################

# C++ project
language: cpp
sudo: false


addons:
# these apt sources will be referenced later (by using *name)
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise-3.9


################
# build matrix #
################

matrix:
  include:

  # GCC 4.9
  - os: linux
    env: COMPILER=g++-4.9
    compiler: gcc
    addons: &gcc49
      apt:
        packages: ["g++-4.9", "g++-4.9-multilib", "libc6-dbg", "libc6-dbg:i386"]
        sources: *apt_sources

  - os: osx
    osx_image: xcode8.3


install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake35 && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake35
      export PATH=${DEPS_DIR}/cmake35/bin:${PATH}
    fi


################
# build script #
################

script:
  # set CXX flag
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - mkdir -p build && cd build
  - cmake .. && cmake --build . --config Release -- -j4
  - ctest -C Release -V
  - cd ..
